FROM python:3.14.5-slim-bookworm

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /src

RUN pip install --upgrade pip wheel "poetry==2.1" setuptools

RUN poetry config virtualenvs.create false

COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root

COPY /src .

CMD ["python", "run.py"]
